Add badges to app
Nastya-Starostenko/test-guru pull request #17
Opened 2022-08-08 07:37 UTC by Nastya-Starostenko

2022-08-08 15:16 UTC, VidgarVii requested changes

2022-08-08 15:16 UTC, VidgarVii commented on app/controllers/admins/badges_controller.rb
> +        :all_tests, :first_test, :level, :count_of_completed_test, :category_id, :test_id, :image_url
Админ при создании баджа должен выбирать тип правила (Категория/лвл и пр) И параметр правила (Ид категории/лвл уровня и пр.) 
В ДЗ заданы 3 типа правила. Но учти что система должна быть готова к масштабировании. И правил может быть сколько угодно.
Где то типы правил надо складывать без раздутия моделей и классов

вторая ошибка в проектировании самой таблицы. При заполнении таблицы у тебя получится почти пусты колонки :level, :category_id, :test_id, :first_try
Такой подход считается очень плохим. Если колонка почти всегда пустая, то скорей всего она не нужна

2022-08-08 15:16 UTC, VidgarVii commented on app/controllers/badges_controller.rb
> +  before_action :badges, only: [:index]
для 1 экшена ни когда колбек не объявляют. Это излишняя сложность, которая еще ухудшает читаемость кода

2022-08-08 15:16 UTC, VidgarVii commented on app/models/badge.rb
> +  belongs_to :test, optional: true
опять же вспоминаем прошлые уроки(
1 belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods
2 Надо соблюдай очередность.
Принято сначала писать belongs_to далее ниже has_
Так мы будем понимать какой код где находится

2022-08-08 15:16 UTC, VidgarVii commented on app/models/test_passage.rb
>      result_in_percent >= SUCCESS_RATIO
`result_in_percent.to_f >= SUCCESS_RATIO`
и проверка на result_in_percent.nil? будет не нужна

2022-08-08 15:16 UTC, VidgarVii commented on app/services/assign_badge_for_user_service.rb
> +  def perform
метод perform зарезервировали для джобов. В сервисах принято называть подобные методы - call

2022-08-08 15:16 UTC, VidgarVii commented on app/services/assign_badge_for_user_service.rb
> +  end
хороший способ. Только обрати внимание, что тут код дублируется. Меняется только название класса. Можно классы вынести в константу. И от DRYить код убрав дублирование. Вспомни урок про валидации на 1 блоке

2022-08-08 15:16 UTC, VidgarVii commented on app/services/assign_badge_for_user_service.rb
> +class AssignBadgeForUserService
не вижу в этом классе кода, который бы назначал бадж юзеру

2022-08-08 15:16 UTC, VidgarVii commented on app/services/badges/base_assign_service.rb
> +    def assign_badges
в этом и дочерних классах происходит 2 вещи.
1 проверка условий баджа
2 выдача баджа юзерам
Я предлагаю разделить эти обязанности в разные классы.
Путь в дочерних классах остаётся проверка
А вот выдачей баджа пусть занимается AssignBadgeForUserService
Т.е. просто перебираем все баджи на условие выдачи. Полученные баджи выдаём юзеру.
И это всё будет происходить 1 раз. А сейчас `user.badges << badges` вызывается каждый раз, что плодит лишние запросы в базу и замедляет работу сервисов

И надо бы сделать тут что-то с неймингами
AssignBadgeForUserService и Badges::BaseAssignService уж больно сильно запутывают понимание, кто чем занимается

2022-08-13 11:54 UTC, VidgarVii requested changes

2022-08-13 11:54 UTC, VidgarVii commented on app/assets/stylesheets/badges.scss
> +}
! Пустую строчку оставить забыл

2022-08-13 11:54 UTC, VidgarVii commented on app/assets/stylesheets/global.scss
> +  //line-height: 60px;
Не используемый код надо удалять, а не комментировать. Сейчас это выглядит как мусор

2022-08-13 11:54 UTC, VidgarVii commented on app/controllers/admins/badges_controller.rb
> +    before_action :badges, only: [:index]
Как я уже писал ранее, для 1 экшена колбек не.... =(

2022-08-13 11:54 UTC, VidgarVii commented on app/javascript/utilities/badge_form.js
> +})
!

2022-08-13 11:54 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :questions, dependent: :restrict_with_error
Хотелось бы узнать причину смены колбека)

2022-08-13 11:54 UTC, VidgarVii commented on app/services/create_badge_service.rb
> +    self.kind = kind
В руби для объявления свойств объекта обычно используют инстанс переменные. @errors =  []

2022-08-13 11:54 UTC, VidgarVii commented on app/services/create_badge_service.rb
> +  def success?
Любой публичный метод должен корректно работать после пораождения объекта. Сейчас .new.success? Вызовите ошибку. В коде ошибка проектирования класса. Посмотри как ты делал сервис создания гист

2022-08-13 11:54 UTC, VidgarVii commented on app/controllers/admins/badges_controller.rb
> +        @badge = Badge.new(image_url: permit_params[:image_url],
Выше есть сервис, который валидирует и создаёт бюдж. Предлагаю чтобы он возвращал не валидный объект с ошибками

2022-08-13 13:11 UTC, VidgarVii requested changes

2022-08-13 13:11 UTC, VidgarVii commented on app/controllers/admins/badges_controller.rb
> +        flash.now[:error] = result.errors.join(', ')
для ошибок валидаций был где то паршл) можно использовать его. Главное чтобы структура объекта с ошибками подходила под паршл. Но это можно как раз сделать

2022-08-13 13:11 UTC, VidgarVii commented on app/controllers/admins/badges_controller.rb
> +        :all_tests, :first_test, :level, :count_of_test, :category_id, :test_id
как я уже писал выше. Такой подход раздувает таблицу с пустыми данными. И ограничивает нас создавать разные правила. Можно обойтись 2мя полями. Тип правила и опция для правиала

2022-08-14 19:27 UTC, Nastya-Starostenko commented on app/models/test.rb
> +  has_many :questions, dependent: :restrict_with_error
Ошибка, хотела добавить валидацию при удалении ответов, исправила

2022-08-14 19:29 UTC, Nastya-Starostenko commented on app/controllers/admins/badges_controller.rb
> +        :all_tests, :first_test, :level, :count_of_test, :category_id, :test_id
Эти данные используются в контроллере, в самой бд только одно поел хранит все кондишены в виде json обьекта, таблицу с пустыми данными это не создает

В целом да, если делать не сложные условия, я выбрала иметь чуть сложнее условия, посмотрите таблицу ещее раз, пожалуйста, если это все еще остается некорректным - я исправлю на два поля

2022-08-15 12:55 UTC, VidgarVii requested changes

2022-08-15 12:55 UTC, VidgarVii commented on app/controllers/admins/badges_controller.rb
> +    end
лучше обойтись 1 методом для фильтрации входящих параметров и не усложнять тут логику.

2022-08-15 12:55 UTC, VidgarVii commented on app/javascript/utilities/badge_form.js
> +  let conditions = document.querySelector('.conditions')
если переменная не переопределяется, то принято считать её константой. Так безопасней

2022-08-15 12:55 UTC, VidgarVii commented on app/javascript/utilities/badge_form.js
> +  }
для удобства работы с этим кодом стоит его абстрагировать на функции, с хорошими названиями, которые будут говорить, что тут вообще происходит 
А еще лучше сделать тут класс с методами. Как в файле ниже. Единообразие кода важный аспект в проекте

2022-08-15 12:55 UTC, VidgarVii commented on app/services/assign_badge_for_user_service.rb
> +  def success?
не исправлено
Как я уже писал, тут ошибка проектирования класса. 
@success = false в конструкторе не решает проблему нарушение логики
new.success? Что в этом случаи мы проверяем? Точно не результат присвоение баджей юзеру. Скорее корректность входящих аргументов конструктора и валидность свойств объекта. Работаем как с обычной структурой данных.
А что проверяется тут ?
`call.success?`
Результат успешности выполнения метода call. И свойства экземпляра класса AssignBadgeForUserService тут совсем не причем. 
Получается что метод  call должен возвращать такой объект, который и будет содержать метод  success? а не self

2022-08-15 12:55 UTC, VidgarVii commented on app/services/assign_badge_for_user_service.rb
> +  def badges
в названии метода лучше указать что за баджи он возвращает.

2022-08-24 14:43 UTC, merged