Add authentification for users
Nastya-Starostenko/test-guru pull request #9
Opened 2022-05-29 12:35 UTC by Nastya-Starostenko

2022-05-29 15:10 UTC, VidgarVii requested changes

2022-05-29 15:10 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @uer = current_user
1 опечатка
2 Этот колбек становится не нужным, так как есть уже метод current_user

2022-05-29 15:10 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>    before_action :set_user, only: :start
для 1 экшена колбек не объявляют. Усложняет читаемость кода

2022-05-29 15:10 UTC, VidgarVii commented on app/controllers/tests_controller.rb
не вижу чтобы при создании теста устанавливался автор. Баг?

2022-05-29 15:10 UTC, VidgarVii commented on app/helpers/flash_helper.rb
> +    render 'shared/flash_messages', messages: flash
ну оочень странный хелпер. Почему бы просто не удалить паршл, а тут написать метод, который будет возвращать хтмл код нужного сообщения, чтобы сделать верстку более управляемой

2022-05-29 15:10 UTC, VidgarVii commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
еще один вариант - использовать доступную в библиотеках ruby регулярку для email - она доступна вот так: `URI::MailTo::EMAIL_REGEXP` (можешь посмотреть в консоли)

2022-05-29 15:10 UTC, VidgarVii commented on config/routes.rb
> +  get :logout, to: 'sessions#destroy'
соблюдай конвенции REST: удаление ресурса (сессии) логично делать через DELETE, а не через GET


будет правильно соблюдать конвенции REST: удаление ресурса (сессии) логично делать через HTTP-метод DELETE, а не через GET (в рельсах именно так и делают)

2022-05-29 19:06 UTC, Nastya-Starostenko commented on app/helpers/flash_helper.rb
> +    render 'shared/flash_messages', messages: flash
Хорошая ли практика, вообще, возвращать из метода хелпера  html  код?

2022-05-30 06:46 UTC, VidgarVii requested changes

2022-05-30 06:46 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @current_user.tests.push(@test)
а если нет такой переменной?
Не просто так создавали хелпер метод current_user

2022-05-30 06:46 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test = Test.new(**test_params.merge(author: @current_user))
на 43 строке пример декларативного стиля. То что надо для ООП.
Тут лучше сделать тоже самое. Используй методы ассоциаций. Не стоит делать лишние операции и усложнять читаемость кода. И обязательно соблюдаем единообразный подход написания кода во всём проекте

2022-06-05 19:20 UTC, merged